defaults: &defaults
  docker:
    - image: isaachinman/awscli-kops
  environment:
    - CI: true
    - PROJECT_IMAGE: "084253039423.dkr.ecr.us-east-1.amazonaws.com/egtutil-forum-invite-generator"
    - GETLOGIN: "aws ecr get-login --no-include-email --region us-east-1"

version: 2
jobs:
  deploy-stage:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Build image
          command: docker build -t egtutil-forum-invite-generator .
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: docker run -it -e CI="true" egtutil-forum-invite-generator yarn lint
      - run:
          name: Export KOPS config
          command: kops export kubecfg --name k8s.eliteguardtraining.com --state=s3://clusters.k8s.eliteguardtraining.com
      - run:
          name: Push CIRCLE_SHA1 tag
          command: LOGIN_STRING=`$GETLOGIN` && ${LOGIN_STRING} && docker tag egtutil-forum-invite-generator:latest $PROJECT_IMAGE:$CIRCLE_SHA1 && docker push $PROJECT_IMAGE:$CIRCLE_SHA1
      - run:
          name: Push stage tag
          command: LOGIN_STRING=`$GETLOGIN` && ${LOGIN_STRING} && docker tag egtutil-forum-invite-generator:latest $PROJECT_IMAGE:stage && docker push $PROJECT_IMAGE:stage
      - run:
          name: Apply new Kubectl configuration
          command: kubectl apply -f .k8s/stage
      - run:
          name: Deploy new image to cluster
          command: kubectl set image deployment/egtutil-forum-invite-generator egtutil-forum-invite-generator=$PROJECT_IMAGE:$CIRCLE_SHA1 -n stage

  deploy-production:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Build image
          command: docker build -t egtutil-forum-invite-generator .
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: docker run -it -e CI="true" egtutil-forum-invite-generator yarn lint
      - run:
          name: Export KOPS config
          command: kops export kubecfg --name k8s.eliteguardtraining.com --state=s3://clusters.k8s.eliteguardtraining.com
      - run:
          name: Push CIRCLE_SHA1 tag
          command: LOGIN_STRING=`$GETLOGIN` && ${LOGIN_STRING} && docker tag egtutil-forum-invite-generator:latest $PROJECT_IMAGE:$CIRCLE_SHA1 && docker push $PROJECT_IMAGE:$CIRCLE_SHA1
      - run:
          name: Push production tag
          command: LOGIN_STRING=`$GETLOGIN` && ${LOGIN_STRING} && docker tag egtutil-forum-invite-generator:latest $PROJECT_IMAGE:production && docker push $PROJECT_IMAGE:production
      - run:
          name: Apply new Kubectl configuration
          command: kubectl apply -f .k8s/production
      - run:
          name: Deploy new image to cluster
          command: kubectl set image deployment/egtutil-forum-invite-generator egtutil-forum-invite-generator=$PROJECT_IMAGE:$CIRCLE_SHA1 -n production

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-stage:
          filters:
            branches:
              only: stage
      - deploy-production:
          filters:
            branches:
              only: master
