apiVersion: v1
kind: Service
metadata:
  name: egtutil-forum-invite-generator
  labels:
    app: egtutil-forum-invite-generator
  namespace: production
spec:
  type: NodePort
  ports:
    - name: egtutil-forum-invite-generator-http
      port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: egtutil-forum-invite-generator
